---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb
  namespace: seat
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 15Gi
  storageClassName: nfs-client
