apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
    name: wordpress
    namespace: blog
spec:
    interval: 5m
    chart:
      spec:
        # renovate: registryUrl=https://itzg.github.io/minecraft-server-charts/
        chart: wordpress
        version: 0.1.1
        sourceRef:
          kind: HelmRepository
          name: k8s-home-charts
          namespace: flux-system
    values:      
      image:
        repository: wordpress
        tag: 5.7.2
        pullPolicy: IfNotPresent      
      nodeSelector:        
        beta.kubernetes.io/arch: arm64