apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
    name: chartmuseum
    namespace: chartmuseum
spec:
    interval: 5m
    chart:
      spec:        
        chart: chartmuseum
        version: 3.3.0
        sourceRef:
          kind: HelmRepository
          name: chartmuseum
          namespace: flux-system
    values:      
      