---
apiVersion: apps/v1   # versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: wordpress
  namespace: reise-blog
  labels:
    app: wordpress
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wordpress
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:        
        backup.velero.io/backup-volumes: wordpress-persistent-storage
      labels:
        app: wordpress
        tier: frontend
    spec:
      containers:
        - image: wordpress:5.8.1
          name: wordpress
          env:
            - name: WORDPRESS_DB_HOST
              value: diskstation:3307
            - name: WORDPRESS_DB_NAME
              value: reise-blog
            - name: WORDPRESS_DB_USER
              value: reise-blog
            - name: WORDPRESS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql
                  key: WORDPRESS_DB_PASSWORD
          ports:
            - containerPort: 80
              name: wordpress
          volumeMounts:
            - name: wordpress-persistent-storage
              mountPath: /var/www/html
      volumes:
        - name: wordpress-persistent-storage
          persistentVolumeClaim:
            claimName: wp-pv-claim