---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: itzg-charts
  namespace: flux-system
spec:
  interval: 30m
  url: https://itzg.github.io/minecraft-server-charts/
  timeout: 2m
