---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: seat
  namespace: seat
  labels:
    app: seat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: seat
  template:
    metadata:
      labels:
        app: seat
    spec:
      containers:
        - name: seat-web
          image: eveseat/seat:4.2.7 
          args: ["web"]
          ports:
            - containerPort: 80
          env:
            - name: DB_HOST
              value: mariadb
            - name: DB_DATABASE
              value: seat
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mariadb
                  key: MARIADB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb
                  key: MARIADB_PASSWORD
            - name: REDIS_HOST
              value: redis
            - name: REDIS_PORT
              value: '6379'
            - name: APP_DEBUG
              value: "false"
            - name: APP_URL
              value: seat.${SECRET_DOMAIN_2}
            - name: APP_KEY
              valueFrom:
                secretKeyRef:
                  name: seat
                  key: app-key
            - name: EVE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: seat
                  key: eve-client-id
            - name: EVE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: seat
                  key: eve-client-secret
            - name: EVE_CALLBACK_URL
              valueFrom:
                secretKeyRef:
                  name: seat
                  key: eve-callback-url
            - name: MAIL_DRIVER
              value: smtp
            - name: MAIL_HOST
              valueFrom:
                secretKeyRef:
                  name: seat
                  key: mail-host
            - name: MAIL_PORT
              valueFrom:
                secretKeyRef:
                  name: seat
                  key: mail-port
            - name: MAIL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: seat
                  key: mail-username
            - name: MAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: seat
                  key: mail-password
            - name: MAIL_ENCRYPTION
              value: tls
            - name: MAIL_FROM_ADDRESS
              valueFrom:
                secretKeyRef:
                  name: seat
                  key: mail-from-address
            - name: MAIL_FROM_NAME
              valueFrom:
                secretKeyRef:
                  name: seat
                  key: mail-from-user
        - name: seat-worker
          image: eveseat/seat:4.2.7 
          args: ["worker"]
          ports:
            - containerPort: 80
          env:
            - name: DB_HOST
              value: mariadb
            - name: DB_DATABASE
              value: seat
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mariadb
                  key: MARIADB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb
                  key: MARIADB_PASSWORD
            - name: REDIS_HOST
              value: redis
            - name: REDIS_PORT
              value: '6379'
            - name: APP_DEBUG
              value: "true"
            - name: APP_URL
              value: seat.${SECRET_DOMAIN_2}
            - name: APP_ENV
              value: local
            - name: APP_KEY
              valueFrom:
                secretKeyRef:
                  name: seat
                  key: app-key
            - name: EVE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: seat
                  key: eve-client-id
            - name: EVE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: seat
                  key: eve-client-secret
            - name: EVE_CALLBACK_URL
              valueFrom:
                secretKeyRef:
                  name: seat
                  key: eve-callback-url
        - name: seat-cron
          image: eveseat/seat:4.2.7 
          args: ["cron"]
          ports:
            - containerPort: 80
          env:
            - name: DB_HOST
              value: mariadb
            - name: DB_DATABASE
              value: seat
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mariadb
                  key: MARIADB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb
                  key: MARIADB_PASSWORD
            - name: REDIS_HOST
              value: redis
            - name: REDIS_PORT
              value: '6379'
            - name: APP_DEBUG
              value: "true"
            - name: APP_URL
              value: seat.${SECRET_DOMAIN_2}
            - name: APP_KEY
              valueFrom:
                secretKeyRef:
                  name: seat
                  key: app-key
            - name: EVE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: seat
                  key: eve-client-id
            - name: EVE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: seat
                  key: eve-client-secret
            - name: EVE_CALLBACK_URL
              valueFrom:
                secretKeyRef:
                  name: seat
                  key: eve-callback-url
      nodeSelector:
        beta.kubernetes.io/arch: amd64