---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: seat
  namespace: seat
  labels:
    app: seat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: seat
  template:
    metadata:
      labels:
        app: seat
    spec:
      containers:
        - name: seat-web
          image: eveseat/seat:4.2.7 
          args: ["web"]
          ports:
            - containerPort: 80
          env:
            - name: DB_HOST
              value: mariadb
            - name: DB_DATABASE
              value: seat
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mariadb
                  key: MARIADB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb
                  key: MARIADB_PASSWORD
            - name: REDIS_HOST
              value: redis
            - name: REDIS_PORT
              value: '6379'
             - name: APP_DEBUG
              value: "true"
            - name: APP_URL
              value: seat.rwcloud.org
            - name: APP_KEY
              value: seat
            - name: EVE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: seat
                  key: eve-client-id
            - name: EVE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: seat
                  key: eve-client-secret
            - name: EVE_CALLBACK_URL
              valueFrom:
                secretKeyRef:
                  name: seat
                  key: eve-callback-url
      nodeSelector:
        beta.kubernetes.io/arch: amd64