apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: seat
  namespace: seat
spec:
  rules:
  - host: seat.rwcloud.org
    http:
      paths:
      - backend:
          service:
            name: seat
            port:
              number: 80
        path: /
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - seat.rwcloud.org