---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: rancher-charts-release-2-6
  namespace: flux-system
spec:
  interval: 60m
  url: https://raw.githubusercontent.com/rancher/charts/release-v2.6
  timeout: 2m