---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: rancher-stable
  namespace: flux-system
spec:
  interval: 60m
  url: https://releases.rancher.com/server-charts/stable
  timeout: 2m