
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: velero
  namespace: velero
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://vmware-tanzu.github.io/helm-charts
      chart: velero
      version: 2.29.6
      sourceRef:
        kind: HelmRepository
        name: vmware-tanzu-charts
        namespace: flux-system
      interval: 5m
  values:
    credentials:
      secretContents:
        cloud: |
          [default]
          aws_access_key_id = ${MINIO_ACCESS_KEY}
          aws_secret_access_key = ${MINIO_SECRET_KEY}
    image:
      repository: velero/velero
      tag: v1.8.1
    configuration:
      provider: aws
      backupStorageLocation:
        name: default
        bucket: velero
        config:
          region: us-east-1
          s3ForcePathStyle: true
          s3Url: http://diskstation:9000
          publicUrl: https://minio.${SECRET_DOMAIN}
      volumeSnapshotLocation:
        name: aws
        config:
          region: us-east-1
      resticTimeout: 6h
    initContainers:
    - name: velero-plugin-for-aws
      image: velero/velero-plugin-for-aws:v1.4.1
      imagePullPolicy: IfNotPresent
      volumeMounts:
      - mountPath: /target
        name: plugins
    resources:
      requests:
        memory: 300Mi
        cpu: 25m
      limits:
        memory: 1500Mi
    # tolerations:
    # - key: "arm"
    #   operator: "Exists"
    # enableHelmHooks: false
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
    snapshotsEnabled: true
    deployRestic: true
    installCRDs: true
    restic:
      podVolumePath: /var/lib/kubelet/pods
      privileged: false
      tolerations:
      - key: "arm"
        operator: "Exists"
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
      resources:
        requests:
          memory: 200Mi
          cpu: 15m
        limits:
          memory: 3000Mi
    # This job upgrades the CRDs.
    upgradeCRDs: false
    
