---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  interval: 1h
  chart:
    spec:
      # renovate: registryUrl=https://grafana.github.io/helm-charts
      chart: longhorn
      version: 100.1.2+up1.2.4
      sourceRef:
        kind: HelmRepository
        name: rancher-charts-release-2-6
        namespace: flux-system
  values:
    longhornManager:
      nodeSelector:
        longhorn: "true"
    longhornDriver:
      nodeSelector:
        longhorn: "true"
    defaultSettings:
      systemManagedComponentsNodeSelector: "longhorn: true"


  