---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "harbor-${SECRET_DOMAIN/./-}"
  namespace: harbor
spec:
  secretName: "harbor-${SECRET_DOMAIN/./-}-tls"
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "harbor.${SECRET_DOMAIN}"
  dnsNames:
  - "harbor.${SECRET_DOMAIN}"
  - "*.harbor.${SECRET_DOMAIN}"