---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rancher-monitoring
  namespace: cattle-monitoring-system
spec:
  interval: 1h
  chart:
    spec:
      chart: rancher-monitoring
      version: 100.1.2+up19.0.3
      sourceRef:
        kind: HelmRepository
        name: rancher-charts-release-2-6
        namespace: flux-system
  values:
    grafana:
      persistence:
        accessModes:
          - ReadWriteOnce
        storageClassName: longhorn
        size: 10G
        subPath: null
        type: pvc
    prometheus:
      prometheusSpec:
        storageSpec:
          volumeClaimTemplate:
            spec:
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 50Gi
              selector:
                matchExpressions: []
                matchLabels: {}
              volumeMode: Filesystem
              storageClassName: longhorn
        