apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: cluster-secrets #this name will also be used for naming the generated kubernetes secret
  namespace: flux-system
spec:
  itemPath: "vaults/k8s/items/cluster-secrets"