---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: hass
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: home-assistant
      version: 12.0.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: homeassistant/home-assistant
      tag: 2022.3.3
    env:
      TZ: "Europe/Berlin"
    hostNetwork: true
    #dnsPolicy: ClusterFirstWithHostNet
    ingress:
      main:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: "nginx"                 
        hosts:
        - host: hass.${SECRET_DOMAIN}
          paths:
          - path: /
            pathType: Prefix
        tls:
        - hosts:
          - hass.${SECRET_DOMAIN}
    prometheus:
      serviceMonitor:
        enabled: true
    probes:
      liveness:
        enabled: true
      readiness:
        enabled: true
      startup:
        enabled: true
    persistence:
      config:
        enabled: true
        storageClass: "nfs-client"
        accessMode: ReadWriteOnce
        size: "10Gi"
    podAnnotations:
      backup.velero.io/backup-volumes: config
    addons:
      codeserver:
        enabled: true
        image:
          repository: codercom/code-server
          tag: 4.0.2
        workingDir: "/config"
        args:
          - --user-data-dir
          - "/config/.vscode"
          - --auth
          - "none"
        ingress:
          enabled: true
          annotations:
            kubernetes.io/ingress.class: "nginx"
            nginx.ingress.kubernetes.io/auth-url: "https://auth.${SECRET_DOMAIN}/oauth2/auth"
            nginx.ingress.kubernetes.io/auth-signin: https://auth.${SECRET_DOMAIN}/oauth2/start
          hosts:
          - host: hass-vscode.${SECRET_DOMAIN}
            paths:
            - path: /
              pathType: Prefix
          tls:
          - hosts:
            - hass-vscode.${SECRET_DOMAIN}
        volumeMounts:
        - name: config
          mountPath: /config
    tolerations:
    - key: "arm"
      operator: "Exists"
    resources:
      limits:
        memory: 2500Mi
      requests:
        cpu: 100m
        memory: 1000Mi    