---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: zigbee2mqtt
  namespace: hass
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: zigbee2mqtt
      version: 7.4.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:    
    env:
      TZ: "Europe/Berlin"
    # Path to your zigbee device in the container
    additionalVolumeMounts:
      - name: raspbee
        mountPath: /dev/ttyACM0
    # Path to your zigbee device on the host
    additionalVolumes: 
      - name: raspbee
        hostPath:
          path: /dev/ttyACM0
    securityContext:
      privileged: true
    persistence:
      data:
        enabled: true
        emptyDir:
          enabled: false
        mountPath: /data
        ## Persistent Volume Storage Class
        ## If defined, storageClassName: <storageClass>
        ## If set to "-", storageClassName: "", which disables dynamic provisioning
        ## If undefined (the default) or set to null, no storageClassName spec is
        ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
        ##   GKE, AWS & OpenStack)
        storageClass: "nfs-client"
        accessMode: ReadWriteOnce
        size: 1Gi
        ## Do not delete the pvc upon helm uninstall
        # skipuninstall: false
        # existingClaim: ""


    # zigbee2mqtt configuration settings
    # https://www.zigbee2mqtt.io/information/configuration.html
    config:
      # These will be applied ONLY on first run
      # Home Assistant integration (MQTT discovery)
      homeassistant: true

      # allow new devices to join
      # WARNING: Disable this after all devices have been paired! (default: false)
      # Note: this will be controllable in the UI
      permit_join: true

      # MQTT settings
      mqtt:
        # MQTT base topic for zigbee2mqtt MQTT messages
        base_topic: zigbee2mqtt
        # MQTT server URL
        server: "mqtt://mosquitto"
        # MQTT server authentication, uncomment if required:
        # user: my_user
        # password: my_password
        # client_id: my_id
        # Alternatively, credentials may be put into a separate file, managed through a secret:
        # password: '!secret password'

        # Optional: Include device information to mqtt messages (default: false)
        include_device_information: true

      # USB / Serial settings
      serial:
        # Location of your zigbee device
        port: /dev/ttyACM0

        # Optional: adapter type, not needed unless you are experiencing problems (options: zstack, deconz)
        adapter: deconz
   
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: feature.node.kubernetes.io/custom-zigbee
              operator: In
              values:
              - "true"
              