---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-secrets
  namespace: flux-system
spec:
  dependsOn:
    - name: crds
  interval: 10m0s
  path: ./deployments/secrets
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
