---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: core
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-secrets
  interval: 10m0s
  path: ./deployments/core
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  postBuild:
    substitute: {}
    substituteFrom:
    #- kind: ConfigMap
    #  name: cluster-settings
    - kind: Secret
      name: cluster-secrets
