---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: crds
  namespace: flux-system
spec:
  dependsOn:
    - name: repositories
    - name: namespaces
  interval: 10m0s
  path: ./deployments/crds
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
