apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
    name: minecraft-caro-maxi
    namespace: minecraft
spec:
    interval: 5m
    chart:
        spec:
            # renovate: registryUrl=https://itzg.github.io/minecraft-server-charts/
            chart: minecraft
            version: 3.6.2
            sourceRef:
                kind: HelmRepository
                name: itzg-charts
                namespace: flux-system
    values:
        image: itzg/minecraft-server
        imageTag: 2021.27.0-java16
        persistence:
          storageClass: "nfs-client"
          dataDir:
            enabled: true
            Size: 10Gi
        resources:
          requests:
            memory: 512Mi
            cpu: 500m
          limits:
            memory: 3048Mi
            cpu: 2000m
        nodeSelector: 
          kubernetes.io/arch: amd64
        #livenessProbe:
        #  initialDelaySeconds: 30
        #  periodSeconds: 5
        #  failureThreshold: 10
        #  successThreshold: 1
        #  timeoutSeconds: 1
        readinessProbe:
          initialDelaySeconds: 30
          periodSeconds: 5
          failureThreshold: 10
          successThreshold: 1
          timeoutSeconds: 1
        startupProbe:
          enabled: true
          failureThreshold: 30
          periodSeconds: 10
        podAnnotations:
          backup.velero.io/backup-volumes: datadir
        extraEnv:
          ENABLE_AUTOPAUSE: "TRUE"
          AUTOPAUSE_TIMEOUT_EST: "600"
          ALLOW_CHEATS: true
        minecraftServer:
          eula: "TRUE"
          version: "LATEST"
          type: VANILLA              
          #jvmOpts: "-Xms512m -Xmx1516m -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1 -Dusing.aikars.flags=https://mcflags.emc.gs -Daikars.new.flags=true"
          memory: 2812M
          difficulty: normal
          maxTickTime: -1
          serviceType: LoadBalancer
          gameMode: creative
          motd: "Caro + Maxi"
          maxPlayers: 3
          whitelist: atlan78,carofox,Maxi_Destrukto
          ops: Atlan78,carofox
          icon: https://www.freeiconspng.com/uploads/minecraft-server-icon-13.png
          loadBalancerIP: ${MINECRAFT_3_LB}
          rcon:
            enabled: false
            port: 25575
            password: "mc-rcon"
            serviceType: LoadBalancer