ssh_authorized_keys:
- ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC50HAq+dwHelVnEyRitojoNetBuVdPPvBOArI0jFg6LdpLwCR0suXb0A3pjFqcMTm/N+h1MHflyuWpHYqefMNeU1k4ymOfQ+jlyoEFFSqVsE8zPO70whSwOP/MGgckllH0O4LuCIi2LXJgU+EuqHAnJAKuhaavRCG+dUh0Z1xDNPy3N0Svo/Z5hRDdmMOunqDFiItIaw+w+zVdDYHNKb25jN5PmjMnATYyZOwOsbdZApOw7tuRgbxxZA+oBqyX94sR2hcm2BUuhj2ZH01XYvhv1PmdxxVHkoFVt0JiSI+1NedCE3cIHE7Pksf6FULwtiEcK5rR4vuXOgUPohwOUnRUi+Vu74nZOugTWPVr5iqlWUNLZR7KYUeqbITf55v9tv5xUd+Xz3bQiRQSDHw35Df9NhOhc8mM/KhqleqIaTVbCiEvd/JO9WeFCSmspWgfu3hkq9EMkOgEepSnQgVfXZS/8882R3SVYAJxipFKhAlzTHlUaUDCQaph4SF9S+WOQsM=
hostname: pi-0
k3os:
  modules:
  - nfs  
  dns_nameservers:
  - 192.168.0.7  
  ntp_servers:
  - 192.168.0.1
  server_url: https://pi-0:6443  
  token: pojirgeoirejgre4390iok34mev
  k3s_args:
  - server
  - "--datastore-endpoint=mysql://k3s:Password2021!@tcp(192.168.0.3:3307)/k3s"
