---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: oauth2-proxy
  namespace: oauth2-proxy
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://oauth2-proxy.github.io/manifests
      chart: oauth2-proxy
      version: 6.3.0
      sourceRef:
        kind: HelmRepository
        name: oauth2-proxy-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: "quay.io/oauth2-proxy/oauth2-proxy"
      tag: "v7.3.0-armv6"
    replicaCount: 1
    nodeSelector: 
      kubernetes.io/arch: arm64
    ingress:
      enabled: true
      path: /oauth2
      hosts:
        - auth.${SECRET_DOMAIN_2}
      tls:
        - hosts:
            - auth.${SECRET_DOMAIN_2}
      annotations:        
        external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN_2}" 
        external-dns.alpha.kubernetes.io/ttl: "120" 
        kubernetes.io/ingress.class: "nginx"
    extraArgs:
      provider: github
      email-domain: "${SECRET_DOMAIN}"
      cookie-domain: .${SECRET_DOMAIN_2}
      whitelist-domain: .${SECRET_DOMAIN_2}
    config:
      existingSecret: "oauth-secrets" 
    authenticatedEmailsFile:
      enabled: true
      restricted_access: |-
        ${EMAIL}
