---
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Alert
metadata:
  name: home-cluster-slack
  namespace: flux-system
spec:
  providerRef:
    name: slack
  eventSeverity: info
  eventSources:
    - kind: GitRepository
      name: '*'
    - kind: Kustomization
      name: '*'
  suspend: false
---
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Alert
metadata:
  name: helmreleases-slack
  namespace: flux-system
spec:
  providerRef:
    name: slack
  eventSeverity: info
  eventSources:
    - kind: HelmRelease
      namespace: 'cert-manager'
      name: '*'
    - kind: HelmRelease
      namespace: 'default'
      name: '*'
    - kind: HelmRelease
      namespace: 'logs'
      name: '*'
    - kind: HelmRelease
      namespace: 'kube-system'
      name: '*'
    - kind: HelmRelease
      namespace: 'monitoring'
      name: '*'
    - kind: HelmRelease
      namespace: 'rook-ceph'
      name: '*'
    - kind: HelmRelease
      namespace: 'velero'
      name: '*'
  suspend: false