apiVersion: v1
kind: Service
metadata:
  name: diskstation
  namespace: ingress-nginx
  labels:
    k8s-app: diskstation
spec:
  type: ClusterIP  
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 5000
  - name: minio
    port: 9000
    protocol: TCP
    targetPort: 9000
   
---
apiVersion: v1
kind: Endpoints
metadata:
  name: diskstation
  namespace: ingress-nginx
  labels:
    k8s-app: diskstation
subsets:
- addresses:
  - ip: 192.168.0.3
  ports:
  - name: http
    port: 5000
    protocol: TCP
  - name: minio
    port: 9000
    protocol: TCP
---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: diskstation
  namespace: ingress-nginx
spec:
  rules:
  - host: ds.${SECRET_DOMAIN}
    http:
      paths:
      - backend:
          service:
            name: diskstation
            port: 
              number: 80
        path: /
        pathType: Prefix
  tls:
    - hosts:
      - ds.${SECRET_DOMAIN}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minio
  namespace: ingress-nginx  
spec:
  rules:
  - host: minio.${SECRET_DOMAIN}
    http:
      paths:
      - backend:
          service: 
            name: diskstation
            port: 
              number: 9000
        path: /
        pathType: Prefix
  tls:
    - hosts:
      - minio.${SECRET_DOMAIN}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: note
  namespace: ingress-nginx
spec:
  rules:
  - host: note.${SECRET_DOMAIN}
    http:
      paths:
      - backend:
          service: 
            name: diskstation
            port: 
              number: 80
        path: /note
        pathType: Prefix
  tls:
    - hosts:
      - note.${SECRET_DOMAIN}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nexus
  namespace: ingress-nginx  
spec:
  rules:
  - host: nexus.${SECRET_DOMAIN}
    http:
      paths:
      - backend:
          service: 
            name: diskstation
            port: 
              number: 38081
        path: /
        pathType: Prefix
  tls:
    - hosts:
      - nexus.${SECRET_DOMAIN}