apiVersion: v1
kind: Service
metadata:
  name: rancher
  namespace: ingress-nginx  
  labels:
    k8s-app: rancher
spec:
  type: ExternalName 
  externalName: rancher.${SECRET_DOMAIN}
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  - name: https
    port: 443
    protocol: TCP
    targetPort: 443
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rancher
  namespace: ingress-nginx
  annotations:
    ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
spec:
  rules:
  - host: rancher.${SECRET_DOMAIN}
    http:
      paths:
      - backend:
          service: 
            name: rancher
            port: 
              number: 443
        path: /
        pathType: Prefix
  tls:
    - hosts:
      - rancher.${SECRET_DOMAIN}

