---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: node-red
  namespace: hass
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: node-red
      version: 9.1.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: nodered/node-red
      tag: 2.0.6-12-minimal
    env:
      TZ: "Europe/Berlin"
      FLOWS: "flows.json"
      NODE_RED_ENABLE_PROJECTS: "true"
      NODE_RED_ENABLE_SAFE_MODE: "false"
    ingress:
      main:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: "nginx"
          nginx.ingress.kubernetes.io/auth-url: "https://auth.${SECRET_DOMAIN_2}/oauth2/auth"
          nginx.ingress.kubernetes.io/auth-signin: https://auth.${SECRET_DOMAIN_2}/oauth2/start
          external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN_2}" 
          external-dns.alpha.kubernetes.io/ttl: "120"
        hosts:
        - host: node-red.${SECRET_DOMAIN_2}
          paths:
          - path: /
            pathType: Prefix
        tls:
        - hosts:
          - "node-red.${SECRET_DOMAIN_2}"
    persistence:
      data:
        enabled: true
        mountPath: /data
        storageClass: "nfs-client"
        accessMode: ReadWriteOnce
        size: "5Gi"
    podAnnotations:
      backup.velero.io/backup-volumes: data
    tolerations:
    - key: "arm"
      operator: "Exists"
    resources:
      requests:
        memory: 350Mi
        cpu: 25m
      limits:
        memory: 500Mi