---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cert-manager.yaml
  - ingress-nginx.yaml  
  - cattle-system.yaml  
  - longhorn-system.yaml
  - snapshot-controller.yaml  
  - monitoring.yaml
  
  