# This file and all contents in it are OPTIONAL.

# The namespace this chart will be installed and restricted to,
# if not specified the chart will be installed to "default"
namespace: ingress-nginx

# Custom helm options
helm:
  # The release name to use. If empty a generated release name will be used
  releaseName: ingress-nginx

  # The directory of the chart in the repo.  Also any valid go-getter supported
  # URL can be used there is specify where to download the chart from.
  # If repo below is set this value if the chart name in the repo
  chart: "ingress-nginx"

  # An https to a valid Helm repository to download the chart from
  repo: "https://kubernetes.github.io/ingress-nginx"

  # Used if repo is set to look up the version of the chart
  version: "3.34.0"

  # Force recreate resource that can not be updated
  force: false

  # How long for helm to wait for the release to be active. If the value
  # is less that or equal to zero, we will not wait in Helm
  timeoutSeconds: 0

  # Custom values that will be passed as values.yaml to the installation
  values:
    controller:
      ingressClass: nginx
      replicaCount: 2
      service:
        type: LoadBalancer
        loadBalancerIP: "192.168.0.240"
        externalTrafficPolicy: Local
      config:
        ssl-protocols: "TLSv1.3 TLSv1.2"
        proxy-body-size: "100m"
        use-forwarded-headers: "true"
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
      extraArgs:
        default-ssl-certificate: "ingress-nginx/ronny-walter-de-tls"
      resources:
        requests:
          memory: 100Mi
          cpu: 100m
        limits:
          memory: 500Mi
