---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: oauth2-proxy
  namespace: oauth2-proxy
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://oauth2-proxy.github.io/manifests
      chart: oauth2-proxy
      version: 4.2.2
      sourceRef:
        kind: HelmRepository
        name: oauth2-proxy-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: "quay.io/oauth2-proxy/oauth2-proxy"
      tag: "v7.1.3-armv6"
    replicaCount: 2
    nodeSelector: 
        beta.kubernetes.io/arch: arm64
    # tolerations:
    #   - key: "arm"
    #     operator: "Exists"
    ingress:
      enabled: true
      path: /oauth2
      hosts: 
        - auth.${SECRET_DOMAIN}
      tls:
      - hosts:
        - auth.${SECRET_DOMAIN}
    extraArgs:
      provider: oidc
      oidc-issuer-url: ${OAUTH_ISSUER_URL}/
      skip-provider-button:
      pass-authorization-header:
      email-domain: "*"
      cookie-domain: .${SECRET_DOMAIN}
      whitelist-domain: .${SECRET_DOMAIN}
    config:
      clientID: ${OAUTH_CLIENT_ID}
      clientSecret: ${OAUTH_CLIENT_SECRET}
      cookieSecret: ${OAUTH_COOKIE_SECRET}
