---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: authentik
  namespace: authentik
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.goauthentik.io
      chart: authentik
      version: 2022.9.0
      sourceRef:
        kind: HelmRepository
        name: authentik-charts
        namespace: flux-system
      interval: 5m
  values:
    # -- Server replicas
    replicas: 1

    worker:
      # -- worker replicas
      replicas: 1

    image:
      repository: goauthentik.io/server
      tag: 2021.12.5
      pullPolicy: IfNotPresent
      pullSecrets: []

    ingress:
      enabled: true
      ingressClassName: ""
      annotations:
        external-dns.alpha.kubernetes.io/hostname: "authentik.${SECRET_DOMAIN_2}"
        external-dns.alpha.kubernetes.io/ttl: "120"
        external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN_2}" 
      labels: {}
      hosts:
        - host: authentik.${SECRET_DOMAIN_2}
          paths:
            - path: "/"
              pathType: Prefix
      tls:
        - hosts:
          - authentik.${SECRET_DOMAIN_2}

    authentik:
      # -- Log level for server and worker
      log_level: info
      # -- Secret key used for cookie singing and unique user IDs,
      # don't change this after the first install
      secret_key: "${SECRET_AUTHENTIK_SECRET_KEY}"
      # -- Path for the geoip database. If the file doesn't exist, GeoIP features are disabled.
      geoip: /geoip/GeoLite2-City.mmdb
      # -- Mode for the avatars. Defaults to gravatar. Possible options 'gravatar' and 'none'
      avatars: gravatar
      email:
        # -- SMTP Server emails are sent from, fully optional
        host: ""
        port: 587
        # -- SMTP credentials, when left empty, not authentication will be done
        username: ""
        # -- SMTP credentials, when left empty, not authentication will be done
        password: ""
        # -- Enable either use_tls or use_ssl, they can't be enabled at the same time.
        use_tls: false
        # -- Enable either use_tls or use_ssl, they can't be enabled at the same time.
        use_ssl: false
        # -- Connection timeout
        timeout: 30
        # -- Email from address, can either be in the format "foo@bar.baz" or "authentik <foo@bar.baz>"
        from: ""
      outposts:
        # -- Template used for managed outposts. The following placeholders can be used
        # %(type)s - the type of the outpost
        # %(version)s - version of your authentik install
        # %(build_hash)s - only for beta versions, the build hash of the image
        docker_image_base: goauthentik.io/%(type)s:%(version)s
      error_reporting:
        # -- This sends anonymous usage-data, stack traces on errors and
        # performance data to sentry.beryju.org, and is fully opt-in
        enabled: false
        # -- This is a string that is sent to sentry with your error reports
        environment: "k8s"
        # -- Send PII (Personally identifiable information) data to sentry
        send_pii: false
      postgresql:
        # -- set the postgresql hostname to talk to
        # if unset and .Values.postgresql.enabled == true, will generate the default
        # @default -- `{{ .Release.Name }}-postgresql`
        host: '{{ .Release.Name }}-postgresql'
        # -- postgresql Database name
        # @default -- `authentik`
        name: "authentik"
        # -- postgresql Username
        # @default -- `authentik`
        user: "authentik"
        password: "${SECRET_AUTHENTIK_POSTGRES_PASSWORD}"
        port: 5432
        s3_backup:
          # -- optional S3 backup, access key
          access_key: "${MINIO_ACCESS_KEY}"
          # -- optional S3 backup, secret key
          secret_key: "${MINIO_SECRET_KEY}"
          # -- optional S3 backup, bucket
          bucket: "authentik"
          # -- optional S3 backup, region
          region: "us-west-1"
          # -- optional S3 backup, host, including protocol (https://minio.domain.tld)
          host: "${MINIO_URL}"
          # -- optional S3 backup, location in the bucket
          # @default -- `"/"`
          location: "/"
          # -- optional S3 backup, set to `true` to disable SSL certificate verification
          insecure_skip_verify: false
      redis:
        # -- set the redis hostname to talk to
        # @default -- `{{ .Release.Name }}-redis-master`
        host: '{{ .Release.Name }}-redis-master'
        password: ""

    # -- see configuration options at https://goauthentik.io/docs/installation/configuration/
    env: {}
    # AUTHENTIK_VAR_NAME: VALUE

    envFrom: []
    #  - configMapRef:
    #      name: special-config

    envValueFrom: {}
    #  AUTHENTIK_VAR_NAME:
    #    secretKeyRef:
    #      key: password
    #      name: my-secret

    service:
      # -- Service that is created to access authentik
      enabled: true
      type: ClusterIP
      port: 80
      name: http
      protocol: TCP
      labels: {}
      annotations: {}

    volumes: []

    volumeMounts: []

    # -- affinity applied to the deployments
    affinity: {}

    resources:
      server: {}
      worker: {}

    # WARNING! When initially deploying, authentik has to do a few DB migrations. This may cause it to die from probe
    # failure, but will continue on reboot. You can disable this during deployment if this is not desired
    livenessProbe:
      # -- enables or disables the livenessProbe
      enabled: true
      httpGet:
        # -- liveness probe url path
        path: /-/health/live/
        port: http
      initialDelaySeconds: 50
      periodSeconds: 10

    readinessProbe:
      enabled: true
      httpGet:
        path: /-/health/ready/
        port: http
      initialDelaySeconds: 50
      periodSeconds: 10

    serviceAccount:
      # -- Service account is needed for managed outposts
      create: true

    prometheus:
      serviceMonitor:
        create: false
        interval: 30s
        scrapeTimeout: 3s
      rules:
        create: false

    geoip:
      # -- optional GeoIP, deploys a cronjob to download the maxmind database
      enabled: false
      # -- sign up under https://www.maxmind.com/en/geolite2/signup
      accountId: ""
      # -- sign up under https://www.maxmind.com/en/geolite2/signup
      licenseKey: ""
      editionIds: "GeoLite2-City"
      image: maxmindinc/geoipupdate:v4.10
      # -- number of hours between update runs
      updateInterval: 8

    postgresql:
      # -- enable the bundled bitnami postgresql chart
      enabled: true
      image:
        registry: docker.io
        repository: bitnami/postgresql
        tag: 14.5.0
        ## Specify a imagePullPolicy
        ## Defaults to 'Always' if image tag is 'latest', else set to 'IfNotPresent'
        ## ref: http://kubernetes.io/docs/user-guide/images/#pre-pulling-images
        ##
        pullPolicy: IfNotPresent
        ## Optionally specify an array of imagePullSecrets.
        ## Secrets must be manually created in the namespace.
        ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
        ## Example:
        ## pullSecrets:
        ##   - myRegistryKeySecretName
        ##
        pullSecrets: []
        ## Set to true if you would like to see extra information on logs
        ## It turns BASH and/or NAMI debugging in the image
        ##
        debug: true

      volumePermissions:
        ## @param volumePermissions.enabled Enable init container that changes volume permissions in the data directory (for cases where the default k8s `runAsUser` and `fsUser` values do not work)
        ##
        enabled: true
      primary:
        nodeSelector: 
          kubernetes.io/arch: amd64
      postgresqlUsername: "authentik"
      postgresqlPassword: "${SECRET_AUTHENTIK_POSTGRES_PASSWORD}"
      postgresqlDatabase: "authentik"
      persistence:
        enabled: true
        storageClass: "nfs-client"
        accessModes:
          - ReadWriteOnce
    redis:
      # -- enable the bundled bitnami redis chart
      enabled: true
      architecture: standalone
      auth:
        enabled: false
      master: 
        nodeSelector: 
          kubernetes.io/arch: amd64
