---
# This file and all contents in it are OPTIONAL.

# The namespace this chart will be installed and restricted to,
# if not specified the chart will be installed to "default"
defaultNamespace: cert-manager

helm:
  # The release name to use. If empty a generated release name will be used
  releaseName: cert-manager

  # The directory of the chart in the repo.  Also any valid go-getter supported
  # URL can be used there is specify where to download the chart from.
  # If repo below is set this value if the chart name in the repo
  chart: "cert-manager"

  # An https to a valid Helm repository to download the chart from
  repo: "https://charts.jetstack.io/"

  # Used if repo is set to look up the version of the chart
  version: "v1.4.0"

  # Force recreate resource that can not be updated
  force: false

  # How long for helm to wait for the release to be active. If the value
  # is less that or equal to zero, we will not wait in Helm
  timeoutSeconds: 0
  values:
    installCRDs: true
    webhook:
      enabled: true
    extraArgs:
    - --dns01-recursive-nameservers=1.1.1.1:53
    - --dns01-recursive-nameservers-only
    cainjector:
      replicaCount: 1
    podDnsPolicy: "None"
    podDnsConfig:
      nameservers:
      - "1.1.1.1"      
    prometheus:
      enabled: true
      servicemonitor:
        enabled: true    