---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tls-rancher-ingress
  namespace: cattle-system
spec:
  secretName: tls-rancher-ingress
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "rancher.${SECRET_DOMAIN_2}"
  dnsNames:
  - "rancher.${SECRET_DOMAIN_2}"  