---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rancher
  namespace: cattle-system
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.jetstack.io/
      chart: rancher
      version: 2.6.2
      sourceRef:
        kind: HelmRepository
        name: rancher-stable
        namespace: flux-system
  values:
    replicas: 1
    hostname: "rancher.${SECRET_DOMAIN_2}"
    ingress:
      extraAnnotations:
        external-dns.alpha.kubernetes.io/hostname: "rancher.${SECRET_DOMAIN_2}"
        external-dns.alpha.kubernetes.io/ttl: "120"        
        external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN_2}"  
        
      tls:
        source: secret
    
