apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
    name: jenkins
    namespace: jenkins
spec:
    interval: 5m
    chart:
      spec:
        # renovate: 
        chart: jenkins
        version: 3.8.4
        sourceRef:
          kind: HelmRepository
          name: jenkins-charts
          namespace: flux-system
        values:
          controller:
            admin:
              existingSecret: "jenkins-admin-secret"
              userKey: jenkins-admin-user
              passwordKey: jenkins-admin-password
            
            # List of plugins to be install during Jenkins controller start
            installPlugins:
          #   - configuration-as-code:1.55
          #   - kubernetes:latest
          #   - workflow-aggregator:latest
          #   - git:latest

            # Set to false to download the minimum required version of all dependencies.
            installLatestPlugins: false

            # Set to true to download latest dependencies of any plugin that is requested to have the latest version.
            installLatestSpecifiedPlugins: false

            # List of plugins to install in addition to those listed in controller.installPlugins
            additionalPlugins: []

            # Enable to initialize the Jenkins controller only once on initial installation.
            # Without this, whenever the controller gets restarted (Evicted, etc.) it will fetch plugin updates which has the potential to cause breakage.
            # Note that for this to work, `persistence.enabled` needs to be set to `true`
            initializeOnce: false

            # Enable to always override the installed plugins with the values of 'controller.installPlugins' on upgrade or redeployment.
            # overwritePlugins: true

            # Configures if plugins bundled with `controller.image` should be overwritten with the values of 'controller.installPlugins' on upgrade or redeployment.
            overwritePluginsFromImage: false

            
            ingress:
              enabled: false
              # Override for the default paths that map requests to the backend
              paths: []
              # - backend:
              #     serviceName: ssl-redirect
              #     servicePort: use-annotation
              # - backend:
              #     serviceName: >-
              #       {{ template "jenkins.fullname" . }}
              #     # Don't use string here, use only integer value!
              #     servicePort: 8080
              # For Kubernetes v1.14+, use 'networking.k8s.io/v1beta1'
              # For Kubernetes v1.19+, use 'networking.k8s.io/v1'
              apiVersion: "extensions/v1beta1"
              labels: {}
              annotations: {}
              # kubernetes.io/ingress.class: nginx
              # kubernetes.io/tls-acme: "true"
              # For Kubernetes >= 1.18 you should specify the ingress-controller via the field ingressClassName
              # See https://kubernetes.io/blog/2020/04/02/improvements-to-the-ingress-api-in-kubernetes-1.18/#specifying-the-class-of-an-ingress
              # ingressClassName: nginx
              # Set this path to jenkinsUriPrefix above or use annotations to rewrite path
              # path: "/jenkins"
              # configures the hostname e.g. jenkins.example.com

              # - secretName: jenkins.cluster.local
              #   hosts:
              #     - jenkins.cluster.local
