apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
    name: jenkins
    namespace: jenkins
spec:
    interval: 5m
    chart:
      spec:
        # renovate: 
        chart: jenkins-operator
        version: 0.6.0
        sourceRef:
          kind: HelmRepository
          name: jenkins-operator-charts
          namespace: flux-system
        valuesFiles:
          - values.yaml 