apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
    name: jenkins
    namespace: jenkins
spec:
    interval: 5m
    chart:
      spec:
        # renovate: 
        chart: jenkins
        version: 3.8.4
        sourceRef:
          kind: HelmRepository
          name: jenkins-charts
          namespace: flux-system
        valuesFiles:
          - valuesXXX.yaml 