---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-workspace
  namespace: jenkins
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 15Gi
  storageClassName: nfs-client
