---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: maven-repo
  namespace: jenkins
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: longhorn-nobackup
