- name: swap  
  hosts: all
  tasks:
    - name: Disable SWAP since kubernetes can't work with swap enabled (1/2)
      shell: |
        /usr/local/bin/k3s-uninstall.sh
    #- name: clear
    #  shell: /usr/local/bin/rke2-uninstall.sh
    #- name: Recursively remove directory
    #  ansible.builtin.file:
    #    path: /var/lib/longhorn
    #    state: absent


