k3s_cluster:    
  hosts:
    pi-0:
      ansible_host: 192.168.0.40
      k3s_control_node: true           
    pi-1:
      ansible_host: 192.168.0.41 
      k3s_control_node: true
    pi-2:
      ansible_host: 192.168.0.42        
      k3s_control_node: true
    pi-3:
      ansible_host: 192.168.0.43
    vm-0:
      ansible_host: 192.168.0.39    
    vm-1:
      ansible_host: 192.168.0.99