k3s_cluster:    
  hosts:
    pi-0:
      ansible_host: 192.168.0.100
      k3s_control_node: true           
    pi-1:
      ansible_host: 192.168.0.101
      k3s_control_node: true
    pi-2:
      ansible_host: 192.168.0.102       
      k3s_control_node: true
    pi-3:
      ansible_host: 192.168.0.103
    vm-0:
      ansible_host: 192.168.0.39    
    vm-1:
      ansible_host: 192.168.0.99
    pc-1:
      ansible_host: 192.168.0.104
    pc-2:
      ansible_host: 192.168.0.105