k3s_cluster:    
  hosts:
    pi-0:
      ansible_host: 192.168.0.40
      k3s_control_node: true      
    pi-1:
      ansible_host: 192.168.0.41            
    pi-2:
      ansible_host: 192.168.0.42        
    pi-3:
      ansible_host: 192.168.0.43
    vm-0:
      ansible_host: 192.168.0.39        