---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nfs-subdir-external-provisioner
  namespace: nfs-subdir-external-provisioner
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner
      chart: nfs-subdir-external-provisioner
      version: 4.0.14
      sourceRef:
        kind: HelmRepository
        name: nfs-subdir-external-provisioner-charts
        namespace: flux-system
  values:
    image:
      repository: k8s.gcr.io/sig-storage/nfs-subdir-external-provisioner
      tag: v4.0.2
    nfs:
      server: diskstation
      path: /volume1/k8s
    storageClass:
      create: true

      # Set a provisioner name. If unset, a name will be generated.
      # provisionerName:

      # Set StorageClass as the default StorageClass
      # Ignored if storageClass.create is false
      defaultClass: true
      # Set a StorageClass name
      # Ignored if storageClass.create is false
      name: nfs-client

      # Allow volume to be expanded dynamically
      allowVolumeExpansion: true

      # Method used to reclaim an obsoleted volume
      reclaimPolicy: Delete
